/**
 * For the detail of `gitCheckout`,
 *                   `withJavaSbtEnv`,
 *                   `scoverage`,
 *                   `deployQuadas`
 * please go to http://192.168.100.5:7777/saas/jenkins-pipeline-library/tree/master/vars
 */

@Library('dsp')
        name = "$docker_package_name$"

node {

    javaHome = tool name: 'JDK8'
    sbtHome = tool name: 'sbt'

    stage('SCM Checkout') {
        gitCheckout "http://git.vpon.com/adx/$docker_package_name$.git"
    }

    stage('Unit Test') {
        withJavaSbtEnv(java: javaHome, sbt: sbtHome) {
            sh 'sbt validate || true'
            junit 'tests/target/test-reports/*.xml'
            scoverage reportDir: './target/scala-2.11/scoverage-report', reportFile: 'scoverage.xml'
        }
    }

    stage('Build') {
        withJavaSbtEnv(java: javaHome, sbt: sbtHome) {
            sh 'sbt package'
        }
    }

    stage("Deploy") {
        withJavaSbtEnv(java: javaHome, sbt: sbtHome) {
            deployQuadas name: name, branch: env.BRANCH_NAME.toLowerCase().replaceAll("[/#]", "").replaceAll("_", "-"), manifest: 'manifest.conf', tarball: 'core/target/universal/app.tgz', pushNomadJsonToS3: true, pushToDockerRegistry: true
        }
    }
}

